# Generated by Django 5.0.4 on 2024-04-15 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default=2, upload_to='teachers'),
            preserve_default=False,
        ),
    ]
